# SPDX-FileCopyrightText: 2021 GNOME Foundation
#
# SPDX-License-Identifier: CC0-1.0

stages:
  - check
  - deploy

flake8:
  stage: check
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E501,E402,F405,W503 --show-source gidocgen

mypy:
  stage: check
  script:
    - dnf install -y python3-mypy
    - mypy --ignore-missing-imports --disallow-incomplete-defs gidocgen
  allow_failure: true

reuse:
  stage: check
  script:
    - dnf install -y reuse
    - reuse lint

pages:
  stage: deploy
  script:
    - dnf install -y make python3-sphinx python3-sphinx_rtd_theme
    - cd docs
    - make
    - mv _build ../public
  artifacts:
    paths:
      - public
  only:
    - main
