stages:
  - check

flake8:
  stage: check
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E501,E402,F405,W503 --show-source gidocgen

mypy:
  stage: check
  script:
    - dnf install -y python3-mypy
    - mypy --ignore-missing-imports --disallow-incomplete-defs gidocgen
